// <auto-generated />
using LPChallenge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LPChallenge.Migrations
{
    [DbContext(typeof(LPChallengeContext))]
    [Migration("20180618200857_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("LPChallenge.Models.Border", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Borders");
                });

            modelBuilder.Entity("LPChallenge.Models.Segment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BorderId");

                    b.Property<int?>("distance");

                    b.Property<string>("feature");

                    b.HasKey("Id");

                    b.HasIndex("BorderId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("LPChallenge.Models.Segment", b =>
                {
                    b.HasOne("LPChallenge.Models.Border")
                        .WithMany("segments")
                        .HasForeignKey("BorderId");
                });
#pragma warning restore 612, 618
        }
    }
}
